basePath: /api/v1
definitions:
  main.ProductRequest:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: Sample Product
        type: string
      price:
        example: 100
        type: integer
    type: object
host: localhost:9000
info:
  contact:
    email: junicodwi.chandra@gmail.com
    name: Junico Dwi Chandra
    url: https://junicochandra.com/
  description: This is a RESTful API service built with Golang for managing data and
    handling requests efficiently.
  title: Golang API Service
  version: "1.0"
paths:
  /get-product:
    post:
      consumes:
      - application/json
      description: Get list of products
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.ProductRequest'
            type: array
        "400":
          description: Bad Request
      summary: Get Product
      tags:
      - Product
swagger: "2.0"
