basePath: /api/v1
definitions:
  user.UserListResponse:
    properties:
      address:
        type: string
      contact:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      email_verified_at:
        type: string
      id:
        type: integer
      last_login_at:
        type: string
      name:
        type: string
      office:
        type: integer
      photo:
        type: string
      role:
        type: integer
      staff_id:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:9000
info:
  contact:
    email: junicodwi.chandra@gmail.com
    name: Junico Dwi Chandra
    url: https://junicochandra.com/
  description: This RESTful API service is developed in Golang using the Gin framework.
    It provides structured endpoints for efficient data management and high-performance
    request handling.
  title: Golang API Service
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get all users from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.UserListResponse'
            type: array
        "400":
          description: Bad Request
      summary: Get all users
      tags:
      - Users
swagger: "2.0"
