basePath: /api/v1
definitions:
  entity.User:
    properties:
      address:
        type: string
      contact:
        type: string
      email:
        type: string
      email_verified_at:
        type: string
      id:
        type: integer
      name:
        type: string
      office:
        type: integer
      password:
        type: string
      photo:
        type: string
      remember_token:
        type: string
      staff_id:
        type: string
      username:
        type: string
    type: object
host: localhost:9000
info:
  contact:
    email: junicodwi.chandra@gmail.com
    name: Junico Dwi Chandra
    url: https://junicochandra.com/
  description: This is a RESTful API service built with Golang for managing data and
    handling requests efficiently.
  title: Golang API Service
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get all users from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "400":
          description: Bad Request
      summary: Get all users
      tags:
      - Users
swagger: "2.0"
